default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 7373
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: beauty_development

test:
  <<: *default
  database: beauty_test

production:
  <<: *default
  database: beauty_production
  username: postgres
  password: 7373
